### PR TITLE
updated hero banner image having issue #2

### PR DESCRIPTION
**Pull request by harsh0728**
updated hero banner background image in place of red background color
Resolved Issue #2 
https://drive.google.com/file/d/1awRFkC3PjbBphTdZWfoyOg6A4b26aAqz/view?usp=sharing

### CODE REVIEW

**Comment by Potato-29** [comment]
You have committed package-lock.json as well, Is it possible that you undo last commit and only push the necessary files? @harsh0728

**Comment by harsh0728** [comment]
> You have committed package-lock.json as well, Is it possible that you undo last commit and only push the necessary files? @harsh0728

@Potato-29 I have not make any changes in package-lock.json 
I think its only because of when i run npm install and some extra dependencies to run the project on my server , thats it nothing else

**Comment by Potato-29** [comment]
but It will cause issue once someone clones the repo, please undo the last commit and push only the changes again

**Comment by harsh0728** [comment]
okay sure

**Comment by harsh0728** [comment]
@Potato-29  now please check and merge it

**Comment by harsh0728** [comment]
@Potato-29  Is there any other issue that i can solve then please share with me

**Comment by Potato-29** [comment]
@harsh0728, I'll create some new issues soon, be posted if you want to work on them, don't worry I'll raise them during hacktoberfest so you guys can work on them while the events is live.

**Comment by harsh0728** [comment]
sure thanks but in my hactoberfest profile , For this pr/mr its showing not accepted till now but you have merged then why

**Comment by Potato-29** [comment]
it updates after awhile don't worry

**Pull request merged**
